import { Pipe, PipeTransform } from '@angular/core';
import { DomSanitizer, SafeHtml } from '@angular/platform-browser';

/**
 * Transforms notification HTML bodies generated by the backend.
 *
 * The backend stores full email HTML (DOCTYPE + body + layout tables + header
 * + footer). This pipe:
 *   1. Extracts the main content cell from the email scaffolding.
 *   2. Strips hardcoded light-mode inline styles (backgrounds, borders, colors)
 *      from <table> / <td> / <p> elements.
 *   3. Injects semantic CSS classes so the frontend theme controls styling.
 *   4. Bypasses Angular DomSanitizer (HTML is server-generated, not user input).
 */
@Pipe({ name: 'notifBody', standalone: true })
export class NotifBodyPipe implements PipeTransform {

  constructor(private sanitizer: DomSanitizer) {}

  transform(html: string | null | undefined): SafeHtml {
    if (!html) return '';

    const doc = new DOMParser().parseFromString(html, 'text/html');

    // ── Step 1: extract main content from full email template ───────────────
    // buildEmail() wraps content in a td styled with padding:28px 32px + color:#374151
    const contentTd = this.findContentTd(doc);
    const source = contentTd
      ? new DOMParser().parseFromString(contentTd.innerHTML, 'text/html')
      : doc;

    // ── Step 2: clean table cells ────────────────────────────────────────────
    source.querySelectorAll<HTMLTableElement>('table').forEach(table => {
      table.removeAttribute('style');
      table.removeAttribute('width');
      table.removeAttribute('cellpadding');
      table.removeAttribute('cellspacing');
      table.classList.add('notif-table');
    });

    source.querySelectorAll<HTMLTableCellElement>('td').forEach(td => {
      const fontWeight = td.style.fontWeight;
      td.removeAttribute('style');
      if (fontWeight) td.style.fontWeight = fontWeight;
      td.classList.add('notif-td');
    });

    // Mark label column (first td in each row → dimmer background)
    source.querySelectorAll<HTMLTableRowElement>('tr').forEach(tr => {
      const cells = tr.querySelectorAll('td');
      if (cells.length >= 2) cells[0].classList.add('notif-td-label');
    });

    // ── Step 3: clean paragraphs ─────────────────────────────────────────────
    source.querySelectorAll<HTMLParagraphElement>('p').forEach(p => {
      if (p.style.color) {
        p.style.removeProperty('color');
        p.classList.add('notif-p-muted');
      }
      // Remove margin from inline style (let CSS handle it)
      if (p.style.margin || p.style.marginBottom) {
        p.style.removeProperty('margin');
        p.style.removeProperty('margin-bottom');
      }
    });

    // ── Step 4: keep badge <span> semantic colors (green/red/yellow/…) ──────
    // Badges use inline style background + color for semantic meaning — leave them.

    const result = source.body.innerHTML;
    return this.sanitizer.bypassSecurityTrustHtml(result);
  }

  /**
   * Identifies the main content <td> inside the email scaffolding generated
   * by buildEmail(). That cell is the one with padding:28px and color:#374151.
   */
  private findContentTd(doc: Document): Element | null {
    const tds = doc.querySelectorAll('td');
    for (const td of Array.from(tds)) {
      const style = td.getAttribute('style') ?? '';
      if (style.includes('28px') && style.includes('#374151')) {
        return td;
      }
    }
    return null;
  }
}
